### ISSUE TITLE
A colon directly after a pair of brackets with at least one character inside them causes the line to display in a reduced font and indented in edit mode

### ISSUE THREAD

**Issue by nhamovitz** [deathau/80s-Neon-for-Obsidian.md#10]
Here's a screenshot of the behavior in edit mode: 
![image](https://user-images.githubusercontent.com/18648574/107139087-51822480-68cd-11eb-9d45-23f59c41b324.png)

It all renders correctly in preview mode, though: 
![image](https://user-images.githubusercontent.com/18648574/107139099-62cb3100-68cd-11eb-9393-3ee572c5d3fe.png)

Here's that text, for reference:
```markdown
Here's some examples:

this [is] fine
but [this]: isn't
this [colon-after-brackets]: thing also changes the syntax highlighting on brackets for some reason
this []: is also fine
so is ]: this
and [: this

happens [when] there are [two]: bracketed pairs in a line
and it [doesn't]: matter which [one] the colon follows
```

**Comment by deathau** [comment]
I don't think this is anything to do with this theme in particular, but a peculiarity of how the syntax highlighter in edit mode interprets the markdown (vs the preview mode)

`[this]:` looks like syntax for the second part of a [reference-style link](https://www.markdownguide.org/basic-syntax#reference-style-links), so the editor is formatting it as such. But since no "first part" for these links exist, they _don't_ render like that in preview mode.

**Comment by nhamovitz** [comment]
Oh, you're totally right. Can't believe I didn't think to check in other themes. Ty for the reply and the CSS, I really like it!
